ALTER TABLE scenes ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 50;
ALTER TABLE scenes ADD COLUMN IF NOT EXISTS tags TEXT;
ALTER TABLE scenes ADD COLUMN IF NOT EXISTS involved_characters TEXT;
